//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marketSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Girdiis
    {
        public int GirdiiID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> GirdiiIrsaliye { get; set; }
        public Nullable<int> GirdiiFiyat { get; set; }
        public Nullable<int> GirdiiMiktar { get; set; }
        public string GirdiiTarih { get; set; }
        public string GirdiiTedarik { get; set; }
    }
}
