//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marketSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteris
    {
        public int MusteriID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int MusteriBorc { get; set; }
    }
}
