//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace marketSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int SatisID { get; set; }
        public int UrunID { get; set; }
        public int UrunFiyat { get; set; }
        public int UrunMiktar { get; set; }
        public string UrunTarih { get; set; }
        public string Ver_Pes { get; set; }
    }
}
